### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by tokyovigilante** [GarlicOS/buildroot#12]
Hi,

I am interested in contributing, and particularly in buiilding a 64-bit version and running custom user-space utilities (mpv, music player etc). Are you able to add build instructions so that the release versions can be generated from the buildroot sources? Thanks.

**Comment by turtleletortue** [comment]
For now we are just using standard Buildroot build commands:
1. First make the garlicos defconfig of the architecture of choice. Ex: "make garlicos_aarch64_defconfig" for aarch64
2. Then just run make to build the rootfs image.

Example:
make garlicos_aarch64_defconfig
make
