### ISSUE TITLE
Feature request: sleep

### ISSUE THREAD

**Issue by benfre** [GarlicOS/buildroot#9]
As of release 2.0.0, there is no sleep function. 

On my rg35xx+, after press power button, at 4s it start to boot, at 18s enter garlicos menu, at 70s finished starting a game.

On stock firmware, it take 1s from sleep, then resume a game play.

Now press power button will shutdown (good thing is shutdown very quickly).

Sleep feature implement: 
1. Press power button to sleep, 
2. Press power button to wake from sleep
3. Sleep, shutdown and reboot from menu

**Comment by Black-Seraph** [comment]
Stock OS doesn't even support sleep, it just turns the screen off & back on again.

As of now, GarlicOS' power button behavior is closer to what one would consider hibernate than sleep.

Future builds will allow bootloaders to configure the power button behavior which should net us sleep support on platforms that support it.

**Comment by benfre** [comment]
What about the third option, adding sleep in menu?
